### ISSUE TITLE
There is no 'Print View' option

### ISSUE THREAD

**Issue by ochebotar** [swimlane/ngx-datatable#1020]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
There is no 'Print View' feature.

**Expected behavior**
Please, add the 'Print View' feature.

**What is the motivation / use case for changing the behavior?**
Motivation is to print the data table.

* **Table version:** 10.2.3

* **Angular version:** 4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by tstackhouse** [comment]
I have an exact use case for this feature.  Currently, if a user prints the page with the table on it, it doesn't resize properly leading to cut off information, and because of the structure of the markup, it is impossible to create a print style sheet that for instance would re-render the table using display: table.  I'm currently exploring a way to output a hidden html `<table>` tag that can be toggled to in my print css.

**Comment by ochebotar** [comment]
Solution? Anyone?

**Comment by amcdnl** [comment]
This is really out of scope for the project. Also this would be very very difficult to do with virtualized dom.

**Comment by tstackhouse** [comment]
For anyone who does come across this and needs it to happen, I was able to flesh out a way to make my proposed feature work by traversing the rendered grid and building out an HTML `<table>` that was swapped out in my print css.  I can't share the code because it's for a work project, plus it's doing some dom manipulation keyed off `ngOnChanges`, so it's kind of gross, though I'd imagine that there's a better, more angular-y way to do it as a plugin or something.  Just sharing my experience from having to "just make it work" for a client.

**Comment by Augustab** [comment]
Does NGX-datatables have support for print-styling today 2021? Example  :host ::ng-deep .datatable-row-odd {
        background-color: #eee;
    } doesent apply to the print, even if i put it inside a @media print tag  @tstackhouse @amcdnl
