### ISSUE TITLE
Virtual scroll - bug on the official example

### ISSUE THREAD

**Issue by konuch** [swimlane/ngx-datatable#1830]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Rows are not rendered when scrolling to the bottom of the table too fast with virtualization enabled.

**Expected behavior**
Rows should be rendered properly even when scrolled fast.

**Reproduction of the problem**
1. Open http://swimlane.github.io/ngx-datatable/#virtual-scroll
2. Grab the scrollbar with your mouse and scroll to the bottom of the table.

**Please tell us about your environment:**
Windows 10 64bit

* **Table version:** 

* **Angular version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 80, Firefox 73.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by davidglezz** [comment]
http://swimlane.github.io/ngx-datatable/#virtual-scroll

Incorrect transform value when scrolling with the scrollbar
![bug](https://user-images.githubusercontent.com/194784/75226759-2df1c700-57ad-11ea-8c3e-18f7f120a51c.gif)

Last item Value when scrolling with the mouse wheel (the correct)
- `transform: translate3d(0px, 893510px, 0px);`
Last item Value when scrolling with the scroll bar
- `transform: translate3d(0px, 888491px, 0px);`

Tested on chrome and firefox

**Comment by migmigmig** [comment]
Ya.  I was having the exact same problem with my datatable implementation.

I went to go check the example on the demos page ("surely I must be doing something wrong!") and it had the exact same problem.

1) When scrolling with the mousewheel, rows are not rendered in quickly and you get a bunch of blank spaces.  On the next mousemove after the wheel stops (I think?) it then renders in.
2) When scrolling with the scrollbar, rows are not rendered in the same way but when you let go of the scrollbar thumb the entire list remains blank.

I was able to fix this by essentially attaching a (scroll) listener and forcing the whole table to refresh (by duplicating my items into a new list).  

After doing this, the list correctly renders in after every scroll event but now my scrolling is at about 1fps.

I specifically chose this tech for my project because it was supposedly "good with virtual scrolling" but this is something of a UX disaster.

**Comment by jmcduffie32** [comment]
I see there's already a PR with a suggested fix for this: https://github.com/swimlane/ngx-datatable/pull/1798

Any chance of getting that PR looked at. This is a pretty bad user experience currently

**Comment by javiersanta** [comment]
Hello, any progress/workarounds on this? I'm having the same issue while scrolling a large set of data.

**Comment by Eloi-Marin** [comment]
I fixed the issue this way. Create a rxjs Subject:

scrollEvent: Subject<void> = new Subject();

then:

this.scrollEvent.pipe(
      debounceTime(100),
      map(_ => this.tableRef.offset),
      distinctUntilChanged(),
).subscribe(() => this.tableRef.element.getElementsByTagName('datatable-body')[0].scrollTop++ );

and for the ngx-datatable scroll output, emit scrollEvent:

[html]
(scroll)="scrollEvent.next()"

Works pretty well with Angular 10.1.1 and ngx-datatable 18.0.0

**Comment by HackPoint** [comment]
> tableRef

With what do you get the tableRef?

**Comment by Eloi-Marin** [comment]
@ViewChild('table') tableRef!: DatatableComponent;

**Comment by marcnee** [comment]
Hi @Hypercubed, any chance to get this bug solved, soon?

**Comment by Hypercubed** [comment]
I have a PR coming that should fix the demo and give some improved details on implementaion: https://github.com/swimlane/ngx-datatable/pull/1991

**Comment by naveenkancherla-shipsy** [comment]
https://github.com/user-attachments/assets/bbe2f1eb-5f14-48bd-92e7-cd0cc9a74a2d

We are facing issues with scrolling while filtering data which has 100+ records in a data table
can any one help
