### ISSUE TITLE
Angular 11 - 'ngx-datatable' is not a known element

### ISSUE THREAD

**Issue by panKt** [swimlane/ngx-datatable#1953]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
`ng serve` fails with
```
'ngx-datatable' is not a known element
```

**Expected behavior**
Should render table

**Reproduction of the problem**
I followed the documentation and it works as expected when `<ngx-datatable>` used in **app.component.html** but fails if I use it in any other module

- **Table version:** 18.0.0
- **Angular version:** 10, 11
- **Browser:** all
- **Language:** all

**Comment by joeveiga** [comment]
@panKt Are you importing `NgxDatatableModule` in your feature module?

**Comment by panKt** [comment]
@joeveiga yes

**Comment by joeveiga** [comment]
@panKt It works as expected on my end. Would you be able to provide a demo? Thanks.

**Comment by chekwube** [comment]
I encounter the same issue on my side ('ngx-datatable' is not a known element) and also this error "error NG8002: Can't bind to 'sortable' since it isn't a known property of 'ngx-datatable-column'." Also I imported NgxDatatableModule in my feature module
I am on Angular 12.1.0. 
Please help me on this issue, Thanks.

**Comment by amadikonda** [comment]
Same error for me , even after importing in feature module. Am using angular 12.0.1.


Error: src/app/dashboard/dashboard.component.html:349:7 - error NG8001: 'ngx-datatable' is not a known element:
1. If 'ngx-datatable' is an Angular component, then verify that it is part of this module.
2. If 'ngx-datatable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 

349       <ngx-datatable class='bootstrap no-detail-row' [columnMode]="'force'" [footerHeight]="50" [rowHeight]="'auto'"
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
350       [rows]="rows" [count]="totalCount" [limit]="dataParams.page_size">
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jasmeensahoo** [comment]
Please help I'm getting same errors from last 3 days and did the same and imported NgxDatatableModule in my feature module
I am on Angular 12.1.0.

**Comment by rishibalan-adappt** [comment]
> 

anwser plz

**Comment by Tokkeri** [comment]
I'm getting this same error anhular 11 and 19.0.0 table.. why is this issue closed without proper answer?!?!?!?!

**Comment by BelangerB** [comment]
This issue persists and yet, it's still closed and no response. That's cool, I guess?

**Comment by ks11281986** [comment]
the solution is simple, Since, we are externally importing the data in the table, so we need to import and register the HttpClientModule in AppModule file.

The step we are performing in app.module.ts we should apply same on XXpage.module.ts

in my case I did for HOME

import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule } from '@ionic/angular';
import { FormsModule } from '@angular/forms';
import { HomePage } from './home.page';
import { HomePageRoutingModule } from './home-routing.module';
import { HttpClientModule } from '@angular/common/http';
import { NgxDatatableModule } from '@swimlane/ngx-datatable';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    HomePageRoutingModule,
    HttpClientModule,
    NgxDatatableModule
  ],
  declarations: [
    HomePage
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class HomePageModule {}
