### ISSUE TITLE
Row Detail Table and docs

### ISSUE THREAD

**Issue by cbeldacap** [swimlane/ngx-datatable#412]
There are no examples on the `demo` folder about Row Detail table. Is there any place where I can check demos of code about all the possibilities that this library offers and, at the same time, see the results I can achieve by using it?

Thnx so much in advance and sorry for not adjusting my issue to the demanded format

Cristóbal

**Comment by s0x** [comment]
Actually you can find the demo here: [Basic > Row Detail](http://swimlane.github.io/ngx-datatable/)
And the corresponding code: [demo/basic/row-detail.ts](https://github.com/swimlane/ngx-datatable/blob/master/demo/basic/row-detail.ts)

**Comment by cbeldacap** [comment]
Yes. there it is. Another thing is that "toggleExpandRow(row)" seems not to work. Expanding all and Collapsing all do work, but not for an specific one. (besides the icons, they're missing). What could be the problem? (just paste what was on the code)

thnx in advance

**Comment by s0x** [comment]
toggleExpandRow works for me. It sounds like it can't find any row which matches your row-parameter. I guess you should check your data (i.e. rows) and make sure there is one rows which matches it.

You can change the icons using the cssClasses property.

**Comment by amcdnl** [comment]
Interesting ... we should probably hook taht to the identifer object if its not already.

**Comment by amcdnl** [comment]
Added new docs in 5.0 release

**Comment by kuncevic** [comment]
Got in to that issue once updated the angular version to 2.5.0.
So the issue is fixed in ngx-datatable 5 as stated above.
But there some breaking changes you have to be aware of:

**.ts**
`this.table.expandAllRows(); => this.table.rowDetail.expandAllRows();`
`this.table.toggleExpandRow(row); this.table.rowDetail.toggleExpandRow(row);`

**template:**
`[detailRowHeight]="xxx"` moved to `ngx-datatable-row-detail` property as `[rowHeight]="xxx"`
