### ISSUE TITLE
Error loading ngx-datatable.js

### ISSUE THREAD

**Issue by leflaco83** [swimlane/ngx-datatable#450]
I'm submitting a 

[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here

**Current behavior**
After following the steps to configure the module I have got this error :

> Failed to load resource: the server responded with a status of 404 (Not Found)
> localhost/:51 (SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/@swimlane/ngx-datatable.js
> 	Error: XHR error (404 Not Found) loading http://localhost:5555/node_modules/@swimlane/ngx-datatable.js
> 	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1485182117414:1039:29) [<root>]
> 	    at Zone.runTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1485182117414:151:47) [<root> => <root>]
> 	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/zone.js/dist/zone.js?1485182117414:345:33) [<root>]
> 	Error loading http://localhost:5555/node_modules/@swimlane/ngx-datatable.js as "@swimlane/ngx-datatable" from http://localhost:5555/app/app.module.js Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues

**Expected behavior**
It is supposed to work fine.

**Reproduction of the problem**
1) Run this npm install @swimlane/ngx-datatable
2) Follow the steps in https://swimlane.gitbooks.io/ngx-datatable/introduction/getting-started.html

**Please tell us about your environment:**
IDE : Visual Studio 2015.
SO : Windows 7

* **Table version:** @swimlane/ngx-datatable": "^5.0.0"

* **Angular version:** 2.0.x

* **Browser:** [all  ]

**Comment by SilWolf** [comment]
Same issue here.

**Comment by amcdnl** [comment]
Please make a repo plunkr. Many ppl have issues with SystemJS (not my fault) so search through the old issues to see if they answered it.

**Comment by d3f3kt** [comment]
Almost everyone who want to use this module in combination with systemjs will have this issue. Just because of the fact that there exist no documentation about the usage with systemjs.
The arrogant attitude of people like @amcdnl is the fundamental problem of this issue. Not everyone is a 'master of javascript' and knows how to configure systemjs. 
So please be so kind and add a short section in your online documentation. Then it is really not longer your fault that user feel left alone with this problem. 


**Back to topic:** 
You can fix it by adding the following line to your systemjs config
```
'@swimlane/ngx-datatable': 'npm:@swimlane/ngx-datatable/release/index.js',
```

**Comment by amcdnl** [comment]
@d3f3kt - Please don't be a troll. 

This is a open-source project that we decided to share with the community. We don't use that setup because it plagued us with issues. Therefore, I don't want to advocate using it either. 

The documentation in logging a issue for this repo literally says please create a demo reproduction case. You want someone to help you but you don't want to put out the effort to help us help you which is why I closed your issue until you do that.

I'm sure someone else in the community could help you with this but with that attitude I wouldn't be surprised if they didn't. If you find a fix and want to share it with other, do a PR and I'll be happy to accept your contribution.

**Comment by d3f3kt** [comment]
Please read my comment carefully again. I didn't creat this issue but I provided a solution how solve it.

**Comment by press0** [comment]
@amcdnl - ngx-datatable looks great but we got the same show stopper error above using : "^7.0.0"

@d3f3kt - Thank You For The Fix.  Otherwise, we would move one

**Comment by Randore** [comment]
Hey, I am using the latest version of Angular `ng new app` and I still see this error message.
Sorry but I a newbie with Angular, can someone help me to fix this.
In older version we have system.js file but what about angular 4, 5
