### ISSUE TITLE
Bug with filtering data

### ISSUE THREAD

**Issue by ritikrishu** [swimlane/ngx-datatable#515]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Filtering data shows total count >0 but no rows are displayed.

**Expected behavior**

See filtered data.

**Reproduction of the problem**

In the demos, on basic => filtering. Go to page offset >3 type *el* in search. Footer shows 15 total entries but no entries are shown.

**What is the motivation / use case for changing the behavior?**

User can search to filter data from any page offset and table should display filtered data properly.

**Please tell us about your environment:**

VS code
* **Table version:** 0.7.x

6.1.2
* **Angular version:** 2.0.x

2.4.7
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by ritikrishu** [comment]
PR: https://github.com/swimlane/ngx-datatable/pull/516 should resolve this issue

**Comment by deeg** [comment]
#516 causes major issues with server side pagination and needs to be reverted, so this bug will need to be fixed another way.

**Comment by amcdnl** [comment]
Per @deeg I have reverted that fix.

**Comment by ritikrishu** [comment]
@deeg @amcdnl see if https://github.com/swimlane/ngx-datatable/pull/549 is a correct approach

**Comment by deeg** [comment]
I am bringing the discussion back here so we can talk about the actual problem at hand.

From what I can tell we both have the same problem. 

**The steps to reproduce are as follows:**

* Navigate to page 4
* Filter your data for the table so that the remaining results have less than 4 pages (2 pages).
    * The mechanism of filter does not matter, could be a client side text filter or a server side facet which re-fetches data
* Now the offset of the table does not change, so you are 'looking at' page 4 when it doesn't really exist. 
* If you click on page one or two which has data, the filtered data would show correctly.

**Correct Behavior**

I believe when the user is filtering/faceting data they always want to go back to the first page. If I'm searing for everything with a certain term, I often want to start at the beginning of the list, not arbitrarily on a middle page.

**The Problem**

...is the library doesn't know if you are filtering data, or just loading a new page from server side pagination.

**Possible Solutions**
* #549 
    * As far as I can tell the solution coded in this PR would take you back to page 2 from the example above. I feel this is incorrect as you really want to go back to page 1.
    * Also if there was enough data to show page 4, it would stay at page 4 which again I don't think is the correct behavior.
* Allow the user to control this behavior themselves by setting the offset manually
    * This already works if you get a hold of the DatatableComponent within your component, you can manually force it to go to any page depending on your situation.
    * Could add change detection to the [offset] input of the DatatableComponent so the user would not have to add `@ViewChild(DatatableComponent) table: DatatableComponent;` to their component if they didn't want to
* Differentiate between paging (mutate the array) and filtering (setting a new array) so the library can tell if you want to stay on the newly loaded page or go back to the first page.
    * Not sure of all the implications of this one yet, and if it would even be possible for the library to differentiate between the two scenarios.


I am leaning towards just letting the user handle it themselves, and adding change detection to the offset input so be able to update it programatically.

@ritikrishu, have I captured your problem correctly? Do you agree that you want to go back to the first page after performing a filtering act?

@amcdnl, thoughts?

**Comment by deeg** [comment]
@amcdnl if we went with solution 2 above one could argue that would be the same thing with sorting, the user could handle itself.

My argument is that when sorting you ALWAYS want to go back to the first page. Since the library can tell when the user is sorting, it should still always force the offset to 0 and we should still merge #553

**Comment by ritikrishu** [comment]
@deeg I agree with your deductions and direction. Emitting input change event is a good approach. To figure if input change is because of filtering or fetching more items would be tricky but that would be a true solution.
