### ISSUE TITLE
Request for dropbox or radio options

### ISSUE THREAD

**Issue by GuofuHuang** [swimlane/ngx-datatable#637]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Can't select one from multiple options. 
**Expected behavior**

Request for Dropbox or radio options
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by adammedford** [comment]
What are you wanting to select from multiple options? You haven't really provided any context to this issue. Why can't this be solved with a header or a cell template? Radio buttons and drop downs are best left to external component libraries because the next complain will be "how do I make this function/appear as my other radio buttons/drop downs?"

**Comment by GuofuHuang** [comment]
I just find out that I can do it using template, sorry I haven't updated this issue, I will close it! 
Thanks!
