### ISSUE TITLE
Row height is not supportable to set as auto when scroll bars are enable

### ISSUE THREAD

**Issue by MorlaRamakrishna** [swimlane/ngx-datatable#777]
I am in need to use scroll bars and multi selection with checkboxes

If I set scrollbars to enable and rowhieght=auto then getting the error like below

vendor.dll.js:61113 EXCEPTION: Uncaught (in promise): Error: Error in ./DatatableComponent class DatatableComponent - inline template:24:8 caused by: Row Height cache initialization failed. Please ensure that 'rowHeight' is a
        valid number value: (auto) when 'scrollbarV' is enabled.
Error: Error in ./DatatableComponent class DatatableComponent - inline template:24:8 caused by: Row Height cache initialization failed. Please ensure that 'rowHeight' is a
        valid number value: (auto) when 'scrollbarV' is enabled.

If I give a fixed number then some rows are missing in table and text wrapping is not possible.

**Please tell us about your environment:**
Operating system: Windows, IDE: Eclipse, package manager: npm

Table version: 6.3.0
Angular version:2.4.x

* **Language:** : TypeScript 2.2.1 | ES6

**Comment by ronnyek** [comment]
I too ran into this one tonight... super confusing. I feel like the error is probably firing as a result of another problem...

**Comment by ronnyek** [comment]
Documentation states this:

Pass undefined for fluid heights, this is not possible in virtual scrolling. Is there some pre-existing function auto could just use that measures it for the cache.

Also, just a question... looks like rowcache currently is only used when virtual scrolling... but if all the rows are the same height because you hardcoded to a value (I realize you could specify a function here) would you even need a row cache for that? Or does it store more than just heights etc.

It seems like if the cache is just storing data, the first time you actually render, you could measure the height of the row and stick that additionally onto the cached row?

[https://swimlane.gitbooks.io/ngx-datatable/content/api/table/inputs.html#rowheight-functionnumberundefined]

**Comment by sbacheld** [comment]
Just ran into this issue myself. Looking at the code for 6.3.0, it appears that using a function for the row height is not supported.

**Comment by amcdnl** [comment]
1) Yes, row cache is only used for virtual scrolling.
2) Its managed natively DOM, its needed for calculating height in virtual scrolling.
3) Yes this is only supported in the later versions.
