### ISSUE TITLE
DataTableFooterComponent: "Cannot read property 'toLocaleString' of undefined"

### ISSUE THREAD

**Issue by AdamVig** [swimlane/ngx-datatable#838]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

When initializing a data table with the below code, the below error is printed to the console.
```JavaScript
<ngx-datatable class="material"
    [rows]="configs"
    [columns]="columns"
    [limit]="10"
    [headerHeight]="50"
    [footerHeight]="50">
</ngx-datatable>
```
The following error (and its corresponding `DebugContext`) is logged to the console four times when I load my page:
```
DataTableFooterComponent.html:20 ERROR TypeError: Cannot read property 'toLocaleString' of undefined
    at Object.eval [as updateRenderer] (DataTableFooterComponent.html:20)
    at Object.debugUpdateRenderer [as updateRenderer] (core.es5.js:13144)
    at checkAndUpdateView (core.es5.js:12293)
    at callViewAction (core.es5.js:12651)
    at execEmbeddedViewsAction (core.es5.js:12609)
    at checkAndUpdateView (core.es5.js:12289)
    at callViewAction (core.es5.js:12651)
    at execComponentViewsAction (core.es5.js:12583)
    at checkAndUpdateView (core.es5.js:12294)
    at callViewAction (core.es5.js:12651)
```
This is the value of the `component` property in the `DebugContext` printed to the console:
![image](https://user-images.githubusercontent.com/5354752/27545873-094747a2-5a5f-11e7-830d-95bedaf02c29.png)

This is confusing to me, because all of the component's values seem to be defined. Also confusing because `DataTableFooterComponent.html:20` points to a line without any bindings on it, but that could just be a sourcemap problem:
![image](https://user-images.githubusercontent.com/5354752/27547047-a90a796e-5a62-11e7-8fc2-5fd262b2bd93.png)

Despite the errors, the footer seems to render correctly:
![image](https://user-images.githubusercontent.com/5354752/27546034-87eb8c9e-5a5f-11e7-80d0-5eb7d3e9172b.png)

**Expected behavior**

The table displays without logging any errors to the console.

**Reproduction of the problem**

The problem happens on page load. Could not reproduce in Plunker. Seems to be related to [this commit](https://github.com/swimlane/ngx-datatable/pull/537/commits/7f6ca7e17ecc624eea49025a4c863b6a52e207d6).

**What is the motivation / use case for changing the behavior?**

This is a bug.

**Please tell us about your environment:**

macOS 10.12.5
VS Code 1.13.1
node 8.0.0, npm 5.0.0
Angular CLI 1.1.3

* **Table version:** 9.3.0

* **Angular version:** 4.2.4

* **Browser:** [all | **Chrome 58.0.3029.110 (64-bit)** | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [**all** | TypeScript X.X | ES6/7 | ES5]

**Comment by dannyvenier** [comment]
Seems from the error that selectedCount is null at some point - could it be that selectedCount is not initialized when the view part of the footer is rendered (on first load) and that is the source of the error.  Then when selectedCount gets set, the binding kicks in and all is good.  However, looking at what you posted, I would expect the footer to say something like "0 selected / 29 total".  It is hard to tell without much of the code.  Also possible that the error message is pointing at rowCount rather than selectedCount, or more likely both since you saw duplicates of the error.  Either way, when the error is thrown, the property is null, likely prior to its initialization.  Take a look at the lifecycle of selectedCount and rowCount to see when they get initialized.

**Comment by LuisUrrutia** [comment]
Have you solved it? I have the same problem and i don't know how to proceed

**Comment by IbrahimElkhatib** [comment]
I faced this issue, in our case it was my teammate mistake, she was initializing the rows as empty object not array

**Comment by ikilled** [comment]
I also faced this issue and figured out that the problem was that I was providing to DataTable **_an Object_** containing multiple Objects (rows) but I should provide **_an Array_** containing multiple Objects.

More specifically, in my case the cause of problem was that the API providing the rows was filtering some results out of all DB results. This filtering caused that the array of rows didn't have sequential keys any more 
 (but something like 2,3,5,8,..) so PHP automatically added "explicit" keys to my array. I solved it by removing these keys with php's function `array_values()` before API sending the response to my front-end Angular App.

**Comment by AdamVig** [comment]
I ended up moving to [Angular Material's `MdTable` component](material.angular.io/components/table/overview), which was released this week. It lacks some of the features that `NgxDatatable` has, but has significantly better scroll performance and will grow more feature-rich over time.

Because of this, I'm unsubscribing from notifications on this issue.

**Comment by anbiniyar** [comment]
FWIW I had the same issue. It seems like I get into this issue if I use lodash cloneDeep() to clone the array. If I don't clone the array, it works just fine for me.

**Comment by hungtruongquoc** [comment]
@LuisUrrutia Thanks. I applied the same solution.

**Comment by mxchange** [comment]
I have a similar issues where in some cases the table would show nothing and no error when `count` is not passed, in other cases it will throw an error. 
Should the count be defaulted to the length of the `rows` when not passed?

**Comment by xxxtonixxx** [comment]
Any news on this?

**Comment by techno2mahi** [comment]
Pls refer this 
[solved](https://github.com/swimlane/ngx-datatable/issues/793#issuecomment-449167947)

**Comment by Usama-Nazir** [comment]
ERROR 💥 TypeError: Cannot read properties of undefined (reading 'toLocaleString')
    at eval (eval at wrap (D:\trybase-master\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:21:1511) 
    at eval (eval at wrap (D:\trybase-master\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:31:4)    
    at template (eval at wrap (D:\trybase-master\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:34:7)
    at exports.renderFile (D:\trybase-master\node_modules\pug\lib\index.js:454:38)
    at exports.renderFile (D:\trybase-master\node_modules\pug\lib\index.js:444:21)
    at exports.__express [as engine] (D:\trybase-master\node_modules\pug\lib\index.js:493:11)
    at View.render (D:\trybase-master\node_modules\express\lib\view.js:135:8)
    at tryRender (D:\trybase-master\node_modules\express\lib\application.js:657:10)
    at Function.render (D:\trybase-master\node_modules\express\lib\application.js:609:3)
    at ServerResponse.render (D:\trybase-master\node_modules\express\lib\response.js:1039:7) {
  statusCode: 500,
  status: 'error'
}
