### ISSUE TITLE
Service with many records taking time to load into NGx datatable

### ISSUE THREAD

**Issue by vibingopal** [swimlane/ngx-datatable#853]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

Hi Team,

We are using datatable component for displaying the records which returned from the service.
On the initial load of the application the datatable is taking  some amount of time to load all the records irrespective of number of records per page. 

Is there any way to restrict load only certain records on page and then load the remaining as per request.
Is we need to configure anything in observable map or by making use of externalPaging attribute ?

We tried with external Paging property but still all the records are getting loaded on first call.Please assist on this.

Version : Angular 4.0.0 
Datatable: 9.3.0

**Comment by adammedford** [comment]
> the datatable is taking some amount of time to load all the records irrespective of number of records per page

It is unclear what you are referring to here. Are you referring to how long it takes for the data table to render your records or how long it takes for your records to be returned from your API service?

External paging requires that your API is capable of handling paging requests. Otherwise, you're just going to make the same request repeatedly rather than getting a subsection of your data per request. To do this you must:
1. Cache the results of your API client side so that you don't re-request records you already have
2. 'Skip' records you've already requested from the API.
3. 'Take' only the number of records you have on each page.

So if you have 10 records per page the request for the 3rd page would skip 20 and take 10.

**Comment by amcdnl** [comment]
Ya, I agree w/ @adammedford .

I recommend using virtual scrolling to handle large amounts of data.
